/**
 * The e-mail marketing knowledge base.
 *
 * Everything here is a technique someone can apply this afternoon, written the
 * way a colleague would explain it: what to do, why it works, and what it looks
 * like when done right. Kept as data so the sheet that displays it stays a
 * presentation component, and so lessons can be counted and ticked off.
 */
export const CHAPTERS = [
  {
    key: 'osnove',
    title: 'Osnove',
    tagline: 'Šta se dešava pre nego što napišete i jednu reč',
    icon: '◆',
    accent: 'sage',
    lessons: [
      {
        id: 'dozvola',
        title: 'Dozvola je jedina prava lista',
        body: 'Kupljene i skinute liste ruše ugled vašeg domena za nedelju dana, a oporavak traje mesecima. Šaljite samo ljudima koji su vam dali adresu: kupcima i onima koji su se prijavili sami.',
        why: 'Pošiljalac se ne ocenjuje po tome šta piše, nego po tome kako ljudi reaguju. Deset žalbi na hiljadu poruka je granica posle koje Gmail počinje da vas šalje u spam — svima, ne samo tim ljudima.',
        do: 'Kod vas su obe grupe čiste: kupci iz arhive i prijave sa sajta. To je sve što vam treba.',
      },
      {
        id: 'jedan-cilj',
        title: 'Jedan mejl, jedan cilj',
        body: 'Svaka poruka ima tačno jednu stvar koju želite da čovek uradi. Ako u istom mejlu nudite tri proizvoda, tražite recenziju i pozivate na Instagram — niko neće uraditi ništa.',
        why: 'Više izbora daje manje odluka. To je isti razlog zašto restoran sa osamdeset jela prodaje manje od onog sa osam.',
        do: 'Pre slanja, pročitajte mejl i pitajte se: koja je jedna radnja? Ako ne možete da odgovorite u jednoj rečenici, izbacujte dok ne budete mogli.',
      },
      {
        id: 'ritam',
        title: 'Ritam je važniji od količine',
        body: 'Bolje jedan mejl svake dve nedelje, uvek, nego pet u martu i ništa do septembra. Ljudi se naviknu na ritam i počnu da ga očekuju.',
        why: 'Duga tišina pa iznenadna poruka izgleda kao da je neko provalio u listu. Odjave i žalbe skoče upravo posle pauze.',
        do: 'Izaberite ritam koji možete da izdržite. Dva mejla mesečno su sasvim dovoljna za prodavnicu kozmetike.',
      },
      {
        id: 'vrednost-pre-prodaje',
        title: 'Na tri prodajna — jedan koji samo pomaže',
        body: 'Mejl koji ništa ne prodaje je ulaganje u to da sledeći bude otvoren. Savet o nezi, objašnjenje sastojka, odgovor na pitanje koje svi postavljaju.',
        why: 'Ljudi otvaraju mejlove pošiljaoca od kog su prošli put dobili nešto korisno. Lista koja dobija samo popuste prestane da otvara za nekoliko meseci.',
        do: 'Šablon „Saveti i edukacija" je napravljen tačno za to.',
      },
    ],
  },
  {
    key: 'naslov',
    title: 'Naslov i preheader',
    tagline: 'Osamdeset odsto posla odluči se pre otvaranja',
    icon: '✦',
    accent: 'clay',
    lessons: [
      {
        id: 'duzina',
        title: 'Trideset do pedeset znakova',
        body: 'Telefon prikazuje oko 35 znakova naslova. Sve preko toga postoji samo za vas. Najvažnija reč ide na početak, nikad na kraj.',
        why: 'Više od polovine vaših kupaca otvara mejl na telefonu, u redu ili u autobusu. Naslov koji se seče na pola nije naslov.',
        do: 'Napišite naslov, pa ga skratite za trećinu. Skoro uvek postane bolji.',
      },
      {
        id: 'preheader',
        title: 'Preheader je drugi naslov, ne nastavak',
        body: 'Preheader je siva linija pored naslova u sandučetu. Ako ga ne napišete, mail klijent uzme prvu rečenicu mejla — obično „Pogledajte u pretraživaču".',
        why: 'Dva reda teksta umesto jednog udvostručuju razlog za otvaranje. Ovo je najčešće propuštena prilika u celom mejl marketingu.',
        do: 'Naslov postavlja pitanje, preheader nagoveštava odgovor. „Perut se vraća?" → „Tri razloga, i šta pomaže već večeras."',
      },
      {
        id: 'bez-velikih-slova',
        title: 'Bez VELIKIH SLOVA, bez tri uzvičnika, bez „besplatno!!!"',
        body: 'Filteri više ne gledaju samo reči, ali ljudi gledaju. Naslov koji viče čita se kao reklama i briše se bez otvaranja.',
        why: 'Poverenje se gradi tonom. Prodavnica koja viče zvuči kao neko ko mora da viče.',
        do: 'Pišite naslov kao da šaljete poruku poznaniku. Malim slovima, bez uzvičnika.',
      },
      {
        id: 'radoznalost-jaz',
        title: 'Ostavite prazninu koju čitalac mora da popuni',
        body: 'Naslov koji kaže sve nema zašto da se otvori. „−15% na šampon" je cela vest. „Zašto smo promenili recepturu šampona" je pitanje.',
        why: 'Mozak loše podnosi nedovršenu informaciju. To je isti mehanizam zbog kog gledate sledeću epizodu.',
        do: 'Ne lažite. Praznina mora biti stvarna i mejl je mora zatvoriti, inače je to klik-mamac i drugi put neće upaliti.',
      },
      {
        id: 'ime-u-naslovu',
        title: 'Ime u naslovu — retko i namerno',
        body: 'Ime podiže otvaranja prvi put, malo manje drugi, a peti put deluje kao mašina. Sačuvajte ga za poruke koje su zaista lične.',
        why: 'Personalizacija radi dok se ne primeti da je automatska. Kad se primeti, radi protiv vas.',
        do: 'Kod vas: „Nedostajete nam, {ime}" ima smisla. „−15%, {ime}" nema.',
      },
      {
        id: 'ime-posiljaoca',
        title: 'Ime pošiljaoca je važnije od naslova',
        body: 'Ljudi prvo gledaju od koga je, pa tek onda šta piše. „Meva Kozmetika" je dobro. „info@" je najgore što možete.',
        why: 'Prepoznavanje pošiljaoca je jedini filter koji čovek primeni za pola sekunde.',
        do: 'Ako prodavnicu vodi osoba, probajte „Eldin iz Meve". Otvaranja obično porastu, jer mejl izgleda kao da ga je pisao čovek.',
      },
    ],
  },
  {
    key: 'struktura',
    title: 'Struktura mejla',
    tagline: 'Kako se slaže poruka koja se pročita do kraja',
    icon: '▤',
    accent: 'forest',
    lessons: [
      {
        id: 'redosled',
        title: 'Kuka, korist, dokaz, poziv, P.S.',
        body: 'Prva rečenica drži pažnju. Zatim šta čitalac dobija. Zatim zašto da vam veruje. Zatim šta da uradi. I na kraju P.S. sa najjačim razlogom.',
        why: 'Ovaj redosled prati način na koji se donosi odluka: pažnja, interes, poverenje, radnja. Preskočite jedan korak i čitalac otpadne baš tu.',
        do: 'Blokovi u editoru su složeni upravo tim redom. Kad dodajete nove, držite se redosleda.',
      },
      {
        id: 'prvi-ekran',
        title: 'Sve važno stane u prvih 300 piksela',
        body: 'Ono što se vidi bez skrolovanja mora samo da kaže o čemu je reč. Veliki logo na vrhu troši taj prostor ni na šta.',
        why: 'Odluka da li se čita dalje pada za dve sekunde, na prvom ekranu.',
        do: 'Logo je mali i ide u podnožje. Na vrhu je poruka.',
      },
      {
        id: 'jedno-dugme',
        title: 'Jedno dugme, ponovljeno — ne pet različitih',
        body: 'Dug mejl sme da ima isti poziv na akciju dva ili tri puta, na različitim mestima. Ali to mora biti isti poziv, na istu stranu.',
        why: 'Ljudi se odlučuju na različitim mestima u tekstu. Dugme im mora biti nadohvat ruke kad se odluče.',
        do: 'Nikad dva različita dugmeta jedno pored drugog. To je izbor, a izbor usporava.',
      },
      {
        id: 'glagol-u-dugmetu',
        title: 'U dugmetu stoji glagol, ne imenica',
        body: '„Poruči šampon" radi bolje od „Proizvodi". „Vidi šta je novo" bolje od „Novosti".',
        why: 'Dugme koje opisuje radnju smanjuje trud potreban za odluku — čovek zna šta će se desiti.',
        do: 'Probajte prvo lice: „Hoću da probam" ume da nadmaši „Probajte".',
      },
      {
        id: 'sirina',
        title: 'Šesto pedeset piksela i jedna kolona',
        body: 'Mejl je širok 600 piksela i ima jednu kolonu. Sve preko dve kolone se na telefonu raspada ili postaje nečitko.',
        why: 'Outlook ne zna za savremeni raspored, a telefon je preuzak za tri kolone. Jedna kolona radi svuda.',
        do: 'Ovo je već ugrađeno — svaki blok koji dodate poštuje to pravilo.',
      },
      {
        id: 'ps',
        title: 'P.S. je drugi najčitaniji red u mejlu',
        body: 'Ljudi skrolaju do kraja pre nego što odluče da čitaju. P.S. vide i oni koji nisu pročitali ništa drugo.',
        why: 'Poslednji red ima privilegiju kraja: pamti se i ne izgleda kao prodaja jer je „dodatak".',
        do: 'U P.S. stavite razlog koji najviše skida prepreku: besplatna dostava, plaćanje pouzećem, rok ponude.',
      },
      {
        id: 'bez-slika',
        title: 'Mejl mora da radi i sa ugašenim slikama',
        body: 'Outlook i mnogi poslovni sanduci ne učitavaju slike dok čovek ne klikne. Ako je vaša poruka na slici, on vidi prazan pravougaonik.',
        why: 'Trećina primalaca vidi prvu verziju mejla bez ijedne slike. Za njih poruka mora da postoji u tekstu.',
        do: 'Nikad ne stavljajte cenu, popust ili poziv na akciju unutar slike. Uvek upišite opis slike (alt).',
      },
      {
        id: 'sto-dva-kb',
        title: 'Preko 102 KB Gmail seče mejl',
        body: 'Gmail preseca poruku i stavi „Prikaži ceo mejl". Tu se gube podnožje, link za odjavu i merenje otvaranja.',
        why: 'Presečen mejl deluje pokvareno, a izgubljen link za odjavu znači da će neko umesto toga prijaviti spam.',
        do: 'Naši šabloni su između 6 i 15 KB. Prostora imate — samo ne lepite tuđi HTML u tekstualni blok.',
      },
    ],
  },
  {
    key: 'psihologija',
    title: 'Psihologija',
    tagline: 'Zašto neko klikne, a neko obriše',
    icon: '❋',
    accent: 'blush',
    lessons: [
      {
        id: 'konkretnost',
        title: 'Konkretno pobeđuje uverljivo',
        body: '„Prirodni sastojci" ne znači ništa. „Maslinovo ulje iz Hercegovine, lavanda, bez sulfata" znači sve.',
        why: 'Detalj se ne može izmisliti lako, pa mozak konkretnost čita kao istinu.',
        do: 'Svuda gde piste opšta reč, zamenite je brojem, imenom ili mestom.',
      },
      {
        id: 'gubitak',
        title: 'Strah od gubitka je jači od želje za dobitkom',
        body: '„Ostalo je još 12 komada iz ove serije" pomera više ljudi nego „Nova serija je stigla".',
        why: 'Gubitak se u odlučivanju broji otprilike dvostruko teže od jednakog dobitka.',
        do: 'Koristite samo kad je istina. Lažna oskudica se prozre iz prvog pokušaja i gubite poverenje zauvek.',
      },
      {
        id: 'uzvracanje',
        title: 'Dajte pre nego što tražite',
        body: 'Savet, uputstvo, mali uzorak uz porudžbinu. Čovek koji je nešto dobio oseća blagu obavezu da uzvrati.',
        why: 'Uzvraćanje je najstarije pravilo trgovine i radi i kad je poklon mali.',
        do: 'Mejl sa savetom pre mejla sa ponudom podiže prodaju drugog mejla, iako prvi ništa ne prodaje.',
      },
      {
        id: 'drustveni-dokaz',
        title: 'Brojevi i imena, ne pridevi',
        body: '„Više od 5.000 porudžbina od 2010." je dokaz. „Naši kupci nas obožavaju." je reklama.',
        why: 'Ljudi gledaju šta rade drugi ljudi kad ne znaju šta da rade sami.',
        do: 'Vi imate stvarne brojeve iz arhive. Koristite ih, tačno onako kako jesu.',
      },
      {
        id: 'prepreke',
        title: 'Uklanjajte prepreke umesto da dodajete razloge',
        body: 'Čovek retko ne kupuje jer nema dovoljno razloga. Ne kupuje jer ga nešto koči: cena dostave, strah da neće raditi, neizvesnost oko plaćanja.',
        why: 'Jedna uklonjena prepreka vredi više od tri dodata argumenta.',
        do: 'Nabrojte tri stvari koje ljudi pitaju pre kupovine i odgovorite na njih u mejlu. Kod vas su to dostava, plaćanje i vreme do rezultata.',
      },
      {
        id: 'prvo-lice',
        title: 'Pišite „vi", a ne „mi"',
        body: 'Prebrojte koliko puta u mejlu piše „mi", „naše", „naša prodavnica". Zamenite većinu sa „vi" i „vaša koža".',
        why: 'Čitaoca zanima šta on dobija, ne šta ste vi postigli.',
        do: 'Jedno mesto gde „mi" ostaje: priča o tome ko pravi proizvod. Tu je „mi" upravo ono što gradi poverenje.',
      },
      {
        id: 'jedna-osoba',
        title: 'Pišite jednoj osobi, ne listi',
        body: '„Dragi kupci" se čita kao saopštenje. „Zdravo Milice" se čita kao poruka.',
        why: 'Mejl se otvara sam, na telefonu, u tišini. Tu nema publike — ima jedan čovek.',
        do: 'Pročitajte mejl naglas. Ako ne zvuči kao nešto što biste rekli jednom čoveku, prepišite ga.',
      },
    ],
  },
  {
    key: 'segmentacija',
    title: 'Segmentacija',
    tagline: 'Isti mejl svima je najskuplja navika',
    icon: '◧',
    accent: 'sage',
    lessons: [
      {
        id: 'zasto-segment',
        title: 'Manja lista donosi više novca',
        body: 'Poruka poslata na 300 ljudi kojima je preparat pri kraju donosi više od iste poruke na 3.000 ljudi nasumično.',
        why: 'Nevažna poruka ne donosi nulu — donosi minus, jer trošite pažnju i izazivate odjave.',
        do: 'U izboru publike stoji koliko je ljudi u svakoj grupi. Uvek izaberite najmanju koja ima smisla.',
      },
      {
        id: 'dopuna',
        title: 'Dopuna je najisplativija poruka u kozmetici',
        body: 'Merite koliko traje pakovanje i pišite nekoliko dana pre nego što se potroši. Ne posle.',
        why: 'Kad se preparat potroši, čovek ionako nešto kupuje. Pitanje je samo da li od vas ili od prvog na koga naiđe.',
        do: 'Grupa „Vreme za dopunu" računa taj razmak iz stvarnih porudžbina svakog kupca, ne iz proseka.',
      },
      {
        id: 'druga-porudzbina',
        title: 'Druga porudžbina je prelomna',
        body: 'Kupac sa jednom porudžbinom je slučajnost. Kupac sa dve je navika. Razmak između prve i druge je mesto gde se gubi najviše ljudi.',
        why: 'Verovatnoća treće kupovine posle druge je višestruko veća nego druge posle prve.',
        do: 'Grupi „Kupili jednom" šaljite uputstvo za upotrebu i molbu za utisak — ne popust.',
      },
      {
        id: 'niz',
        title: 'Niz mejlova umesto jednog',
        body: 'Dobrodošlica nije jedan mejl nego tri: priča, uputstvo, ponuda. Napuštena korpa je dva: podsetnik, pa razlog.',
        why: 'Jedan mejl stigne u pogrešnom trenutku. Tri mejla u deset dana pogode nekoga u pravom.',
        do: 'Napravite ih kao odvojene kampanje i šaljite sa razmakom. Isti šablon, drugi naslov, drugi ugao.',
      },
      {
        id: 'neaktivni',
        title: 'Čistite listu, i to namerno',
        body: 'Ko nije otvorio ništa šest meseci — pošaljite mu jedan mejl za vraćanje. Ako ni to ne otvori, sklonite ga.',
        why: 'Mrtve adrese obaraju vaš prosek otvaranja, a Gmail taj prosek koristi da odluči gde ide vaša pošta za sve ostale.',
        do: 'Manja i živa lista stiže u sanduče. Velika i mrtva lista završava u spamu — i za one koji bi vas čitali.',
      },
      {
        id: 'vreme-slanja',
        title: 'Vreme slanja: probajte, ne verujte tabelama',
        body: 'Utorak u 10 je opšte pravilo koje ne važi za sve. Za kozmetiku kod nas često bolje rade veče radnim danom i nedelja ujutru.',
        why: 'Vaša publika ima svoj raspored. Jedini način da ga saznate je da isprobate dva termina na istoj poruci.',
        do: 'Podelite grupu na pola, pošaljite u dva termina, uporedite. Dva puta je dovoljno da vidite obrazac.',
      },
    ],
  },
  {
    key: 'isporuka',
    title: 'Isporučivost',
    tagline: 'Najlepši mejl ne vredi ništa iz spam foldera',
    icon: '⛊',
    accent: 'forest',
    lessons: [
      {
        id: 'spf-dkim-dmarc',
        title: 'SPF, DKIM i DMARC — tri zapisa bez kojih nema ničega',
        body: 'To su tri unosa u DNS-u koji dokazuju da mejl zaista dolazi od vas. Bez njih Gmail i Yahoo od 2024. odbijaju masovne pošiljaoce.',
        why: 'Bez potpisa vaš mejl izgleda isto kao mejl nekoga ko se lažno predstavlja kao vi.',
        do: 'Resend vam ispiše tačne zapise kad dodate domen. Upišite ih i sačekajte da pokaže „verified" pre prvog slanja.',
      },
      {
        id: 'poddomen',
        title: 'Šaljite sa poddomena, ne sa glavnog',
        body: 'Koristite nešto kao posta.meva.life za kampanje, a glavni domen ostavite za lične poruke i potvrde porudžbina.',
        why: 'Ako kampanja jednom naudi ugledu, šteta ostaje na poddomenu. Vaše lične poruke i dalje stižu.',
        do: 'Ovo se podešava jednom, na početku. Kasnija promena domena znači da počinjete zagrevanje ispočetka.',
      },
      {
        id: 'zagrevanje',
        title: 'Zagrevanje: ne šaljite 4.000 mejlova prvog dana',
        body: 'Nov domen sa nula istorije koji odjednom pošalje hiljade poruka izgleda tačno kao provaljen nalog.',
        why: 'Poštanski serveri sude po istoriji. Nemate je — pa je pravite postepeno.',
        do: 'Prvi dan 200, pa 400, pa 800, duplirajte na svaka dva dana. Prvo šaljite najboljim kupcima, jer oni otvaraju — a dobra reakcija je ono čime se gradi ugled.',
      },
      {
        id: 'list-unsubscribe',
        title: 'Dugme za odjavu u samom sandučetu',
        body: 'Zaglavlje List-Unsubscribe tera Gmail da pored vašeg imena prikaže svoje dugme „Odjavi se".',
        why: 'Kad odjava nije laka, ljudi umesto nje pritisnu „Prijavi spam". Jedna žalba šteti hiljadu puta više od jedne odjave.',
        do: 'Već je ugrađeno u svaku poruku koju ovde pošaljete, zajedno sa jednim klikom bez logovanja.',
      },
      {
        id: 'tekstualna-verzija',
        title: 'Uvek i tekstualna verzija',
        body: 'Svaki mejl nosi dve verzije: HTML i običan tekst. Poruka koja ima samo HTML dobija lošiju ocenu kod filtera.',
        why: 'Pravi mejlovi istorijski nose obe. Samo mašine šalju jednu.',
        do: 'Gradi se sama, iz istih blokova. Ne morate ništa da radite.',
      },
      {
        id: 'zamke',
        title: 'Stare adrese iz arhive su rizik',
        body: 'Adresa od pre pet godina može biti ugašena i pretvorena u zamku za spamere. Slanje na nju direktno obara ugled.',
        why: 'Zamke postoje baš zato da uhvate one koji šalju na stare, nepročišćene liste.',
        do: 'Vaših 3.964 kupaca šaljite u talasima, od najskorijih ka najstarijim. Ako grupa od pre četiri godine ima puno odbijanja, stanite i preskočite ostatak.',
      },
      {
        id: 'skracivaci',
        title: 'Bez skraćivača linkova',
        body: 'bit.ly i slični u mejlu su signal za spam, jer sakrivaju odredište.',
        why: 'Filteri gledaju ugled svakog domena u poruci. Skraćivače koriste i spameri, pa im je ugled loš po difoltu.',
        do: 'Pišite pune adrese ka meva.life. Dodajte utm oznake — one ne škode i daju vam merenje.',
      },
      {
        id: 'odgovor',
        title: 'Neka adresa za odgovor bude prava',
        body: 'noreply@ je propuštena prilika i loš signal. Neka ljudi mogu da odgovore, i odgovarajte im.',
        why: 'Odgovor na vaš mejl je najjači pozitivan signal koji Gmail vidi. Nekoliko odgovora podiže isporučivost cele liste.',
        do: 'U prvom mejlu pozovite ljude da odgovore — pitanjem o tipu kože, na primer. To je trik koji retko ko koristi.',
      },
    ],
  },
  {
    key: 'merenje',
    title: 'Merenje',
    tagline: 'Šta se zaista broji, a šta više ne znači ništa',
    icon: '◵',
    accent: 'clay',
    lessons: [
      {
        id: 'otvaranja',
        title: 'Otvaranja više nisu pouzdana',
        body: 'Apple od 2021. unapred učita sliku za merenje otvaranja za sve svoje korisnike. Njihova otvaranja su lažna.',
        why: 'Skoro polovina vaših kupaca je na iPhone-u. To znači da vam je stopa otvaranja naduvana i da po njoj ne smete da odlučujete.',
        do: 'Gledajte klikove i porudžbine. Otvaranja koristite samo da uporedite dva naslova na istoj listi u isto vreme.',
      },
      {
        id: 'prihod-po-mejlu',
        title: 'Jedina prava mera: prihod po poslatoj poruci',
        body: 'Podelite prihod kampanje brojem poslatih mejlova. Taj broj kaže da li se slanje isplatilo.',
        why: 'Stopa klikova može da raste dok prihod pada. Prihod po poruci ne može da vas slaže.',
        do: 'Označite linkove sa utm_campaign i uporedite u analitici. Generator oznaka je na strani Marketing.',
      },
      {
        id: 'ab',
        title: 'Testirajte jednu stvar, ne pet',
        body: 'Promenite samo naslov, ili samo dugme. Ako promenite sve odjednom, znaćete da je bolje, ali ne i zašto.',
        why: 'Bez izolovane promene nema zaključka koji možete da ponovite.',
        do: 'Kod liste od par hiljada ljudi, razlike manje od 20% su najčešće slučajnost. Ne menjajte strategiju zbog njih.',
      },
      {
        id: 'odjave',
        title: 'Odjave ispod 0,5% su normalne',
        body: 'Odjava nije neuspeh. Neuspeh je žalba na spam — nju držite ispod jedne na hiljadu poruka.',
        why: 'Ko se odjavio, ionako ne bi kupio. Ko je prijavio spam, šteti isporuci svima ostalima.',
        do: 'Ako odjave pređu 1%, poruka je bila nevažna toj grupi. Problem je u segmentaciji, ne u tekstu.',
      },
    ],
  },
  {
    key: 'cake',
    title: 'Sitne čake',
    tagline: 'Ono što se ne piše u vodičima',
    icon: '✧',
    accent: 'blush',
    lessons: [
      {
        id: 'nevidljivi-razmak',
        title: 'Sakrijte prvi red mejla iz pregleda',
        body: 'Posle preheadera ide niz nevidljivih znakova koji potisnu ostatak teksta iz pregleda u sandučetu.',
        why: 'Bez toga Gmail pored preheadera nastavi da prikazuje prvu rečenicu mejla — pa se ista poruka vidi dvaput.',
        do: 'Ugrađeno je u svaku poruku ovde. To je trik koji koriste velike marke, a skoro niko ne primeti.',
      },
      {
        id: 'ime-fajla',
        title: 'Imenujte slike opisno',
        body: 'sampon-za-osetljivu-kozu.jpg umesto IMG_4471.jpg.',
        why: 'Filteri gledaju i imena fajlova. Nasumični nizovi izgledaju kao nešto što se krije.',
        do: 'Sitnica koja ništa ne košta, a čita se kao uredan pošiljalac.',
      },
      {
        id: 'emoji',
        title: 'Emodži u naslovu — najviše jedan, i to na kraju',
        body: 'Jedan emodži ume da podigne otvaranja. Dva ili tri ih obore, jer izgleda kao masovna pošta.',
        why: 'Emodži privlači oko dok je redak. Kad se pojavi u svakom naslovu, postaje šum.',
        do: 'Nikad emodži u naslovu koji nosi lošu vest ili ozbiljan sadržaj.',
      },
      {
        id: 'ponovno-slanje',
        title: 'Pošaljite isti mejl ponovo, samo onima koji nisu otvorili',
        body: 'Tri dana kasnije, isti sadržaj, drugi naslov, samo neotvarači.',
        why: 'Dvadeset do trideset odsto ljudi otvori iz drugog pokušaja. To je najjeftiniji prihod u mejl marketingu — tekst je već napisan.',
        do: 'Šablon „Podsetnik" postoji baš za to. Nikad ne šaljite isti naslov, jer ga je čovek već video i preskočio.',
      },
      {
        id: 'sirotinjski-tekst',
        title: 'Mejl koji izgleda kao da ga niste dizajnirali',
        body: 'Obična poruka bez slika i dugmadi, kao da ste je otkucali sami. Radi neverovatno dobro, naročito za vraćanje kupaca.',
        why: 'Izgleda lično, pa se otvara i čita. Filteri je takođe propuštaju lakše od šarene poruke.',
        do: 'Napravite je od dva bloka: tekst i P.S. Bez slike, bez dugmeta — samo link u rečenici.',
      },
      {
        id: 'pitanje',
        title: 'Završite pitanjem i tražite odgovor',
        body: '„Kakva vam je koža glave zimi — suva ili masna? Odgovorite mi, pročitaću svaki odgovor."',
        why: 'Odgovori govore poštanskom serveru da ste neko sa kim se ljudi dopisuju. Malo šta toliko podiže isporučivost.',
        do: 'Kao bonus, saznaćete kako da segmentirate listu — i imaćete materijal za sledeći mejl.',
      },
      {
        id: 'cena-u-preheaderu',
        title: 'Stavite cenu u preheader, ne u naslov',
        body: 'Naslov nosi razlog, preheader nosi broj.',
        why: 'Cena u naslovu mejl odmah svrsta u reklame. Cena u preheaderu je informacija za onog ko je već zainteresovan.',
        do: '„Nova serija sapuna" + „Ograničeno na 60 komada, 890 RSD."',
      },
      {
        id: 'utorak-nije-pravilo',
        title: 'Šaljite kad vaši kupci kupuju',
        body: 'Iz vaše analitike znate u koje dane i sate stižu porudžbine. To je vaše najbolje vreme za slanje.',
        why: 'Čovek je u „modu kupovine" u istim satima u kojima je i prošli put kupio.',
        do: 'Na strani Pregled stoji koji su vam dani i sati najjači. Pošaljite sat vremena pre vrha.',
      },
      {
        id: 'ne-menjaj-poslato',
        title: 'Poslata kampanja se ne menja',
        body: 'Posle slanja kampanja postaje zapis o tome šta je tačno otišlo.',
        why: 'Kad se za mesec dana pitate zašto je jedna poruka prošla bolje, jedini pouzdan odgovor je tekst koji je zaista poslat.',
        do: 'Editor ovo sprovodi sam: poslata kampanja se otvara, čita i umnožava, ali se ne prepravlja.',
      },
    ],
  },
]

/** Every lesson in the book, flattened — used for counting progress. */
export const ALL_LESSONS = CHAPTERS.flatMap((chapter) =>
  chapter.lessons.map((lesson) => ({ ...lesson, chapter: chapter.key })),
)
